const contactType = {
    SCHEDULE_SURGERY: "SCHEDULE_SURGERY",
    TALK_TO_INSURANCE_ADVISOR: "TALK_TO_INSURANCE_ADVISOR",
    QUICK_EMI_CHECK: "QUICK_EMI_CHECK",
    REQUEST_CALLBACK: "REQUEST_CALLBACK",
    QUICK_DOCTOR_CONNECT: "QUICK_DOCTOR_CONNECT",
    FREE_CONSULTATION: "FREE_CONSULTATION",
    FREE_CONSULTATION_WITH_DETAILS: "FREE_CONSULTATION_WITH_DETAILS",
    CONDITION_CONSULTATION: "CONDITION_CONSULTATION",
}

const ROLE = {
    SUPER_ADMIN: "SUPER_ADMIN",
    ADMIN: "ADMIN",
    USER: "USER"
}

export { contactType, ROLE }